
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class VoiceProvider(Protocol):
    async def connect(self) -> None: ...
    async def send_audio_chunk(self, chunk: bytes) -> None: ...
    async def receive_audio_chunk(self) -> bytes | None: ...
    async def interrupt(self) -> None: ...
    async def close(self) -> None: ...
